### ISSUE TITLE
[TODO List]

### ISSUE THREAD

**Issue by Doragd** [MLNLP-World/AI-Paper-Collector#100]
- [ ] 目前的conference list是硬编码在源文件中，当新增会议时，无法自动更新。理想的解决方案是这部分也从后端数据中获取：https://github.com/MLNLP-World/AI-Paper-Collector/blob/eb0f74944407d01a7e3d398ce55acf39545fa29d/web-vue/src/components/AdvancedSettingDlg.vue#L35 https://github.com/MLNLP-World/AI-Paper-Collector/blob/eb0f74944407d01a7e3d398ce55acf39545fa29d/web-vue/src/views/HomeView.vue#L28
- [ ] 目前网站搜索结果页左侧显示的会议和结果list无法完整显示，需要向下滑动，理想的解决方案是平铺在页面中间
- [ ] 目前结果页的摘要是在悬浮窗口中显示，容易遮挡其他元素，期待取消这种显示方式，直接更新到结果卡片中
- [ ] 目前网站仅支持简单的字符串匹配，没有类似arxiv那种支持or and查询
- [ ] 按照hot，year，conf排序功能在切换另一种排序方式时无法正常起作用
